import os
import sys
import json
import subprocess
from pathlib import Path
from crewai import Agent, Task, Crew, Process
from langchain_groq import ChatGroq

# 1. CONFIG
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
SBOM_FILE = "vulpy-sbom.json"
SEMGREP_OUTPUT = "semgrep-results.json"

if not GROQ_API_KEY:
    print("ERROR: GROQ_API_KEY not set")
    sys.exit(1)

llm = ChatGroq(
    groq_api_key=GROQ_API_KEY,
    model_name="llama-3.3-70b-versatile",
    temperature=0.1
)

# 2. AGENTES ALINEADOS AL JD

sast_agent = Agent(
    role='SAST Security Engineer',
    goal='Find code vulnerabilities using OWASP Top 10 and CWE mapping. Analyze semgrep results.',
    backstory='Expert in static analysis. You map findings to OWASP Top 10 and CWE. You do secure code review.',
    llm=llm,
    verbose=True
)

sca_agent = Agent(
    role='SCA Dependency Analyst', 
    goal='Analyze SBOM for known vulnerabilities. Check transitive dependencies and CVEs.',
    backstory='You are an expert in Software Bill of Materials and open-source vulnerability scanning. You correlate pkg:purl with CVE database.',
    llm=llm,
    verbose=True
)

redteam_agent = Agent(
    role='Red Team Lead',
    goal='Prioritize risks and suggest exploits. Map findings to OWASP Top 10 and ASVS.',
    backstory='You think like an attacker. You validate if a vuln is exploitable and suggest fixes.',
    llm=llm,
    verbose=True
)

# 3. TASKS

def load_sbom():
    with open(SBOM_FILE) as f:
        sbom = json.load(f)
    components = []
    for c in sbom.get("components", []):
        components.append(f"{c['name']}@{c.get('version', 'unknown')} - purl: {c.get('purl', '')}")
    return "\n".join(components)

def run_semgrep():
    print("Running Semgrep SAST...")
    subprocess.run([
        "semgrep", "--config=auto", "--json", "-o", SEMGREP_OUTPUT, "."
    ], capture_output=True)
    with open(SEMGREP_OUTPUT) as f:
        return json.load(f)

sbom_data = load_sbom()
semgrep_data = run_semgrep()

sast_task = Task(
    description=f"""Analyze these Semgrep findings and map to OWASP Top 10 and CWE.
    Findings: {json.dumps(semgrep_data)[:4000]}
    Return: Vulnerability, Severity, OWASP, CWE, File, Line, Fix""",
    agent=sast_agent,
    expected_output="Markdown table of SAST findings with OWASP/CWE mapping"
)

sca_task = Task(
    description=f"""Analyze this SBOM for known CVEs. Focus on Critical and High.
    SBOM Components:
    {sbom_data}
    Known vulnerable: chromadb@1.1.1 CVE-2026-45829 SQLi, click@8.1.8 CVE-2026-7246 Command Injection
    Return: Package, Version, CVE, Severity, CVSS, Description, Fix Version""",
    agent=sca_agent,
    expected_output="Markdown table of SCA findings with CVEs"
)

consolidation_task = Task(
    description="""Consolidate SAST and SCA results. Prioritize by risk.
    Add: 1. Summary 2. Top 3 risks 3. CI/CD Gate recommendation: FAIL or PASS
    Follow ASVS and OWASP standards.""",
    agent=redteam_agent,
    context=[sast_task, sca_task],
    expected_output="Executive security report in Markdown"
)

# 4. CREW
crew = Crew(
    agents=[sast_agent, sca_agent, redteam_agent],
    tasks=[sast_task, sca_task, consolidation_task],
    process=Process.sequential,
    verbose=2
)

# 5. RUN
print("Starting Vulpy AI Security Scan...")
result = crew.kickoff()

report = f"""# Vulpy AI Security Report

{result}

---
*Generated by Vulpy v2.0 - AI-Enabled AppSec*
"""

with open("vulpy-report.md", "w") as f:
    f.write(report)

print("Report generated: vulpy-report.md")

# 6. CI/CD GATE
if "Critical" in result or "High" in result:
    print("::error::Security gate FAILED. Critical/High vulnerabilities found.")
    sys.exit(1)
else:
    print("Security gate PASSED")
    sys.exit(0)